openapi: "3.0.2"
info:
  title: Reservations Api
  version: "0.0.1"
servers:
  - url: http://localhost:7353
tags:
  - name: Server
    description: Server information
paths:
  /status:
    get:
      tags:
        - Server
      summary: Get server status
      responses:
        "200":
          description: Status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
