version: "3.7"
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./src:/src
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - nginx
    depends_on:
      - php
  php:
    build:
      context: .
    working_dir: /src
    environment:
      - APP_NAME=Reservations
      - APP_ENV=production
      - APP_KEY=
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=reservations
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    networks:
      default:
        aliases:
          - php
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - db
networks:
  default:
