version: "3.7"
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./src:/src
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      default:
        aliases:
          - nginx
  php:
    image: php:7.3-fpm-buster
    volumes:
      - ./src:/src
    networks:
      default:
        aliases:
          - php
networks:
  default: