version: "3.7"
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./src:/src
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src
    ports:
      - 7353:80
    networks:
      default:
        aliases:
          - nginx
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: dockerfile-dev
    volumes:
      - ./src:/src
    working_dir: /src
    networks:
      default:
        aliases:
          - php
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "SuperSecret"
    volumes:
      - ./configs/servers.json:/pgadmin4/servers.json
    networks:
      default:
        aliases:
          - pgadmin
    ports:
      - 7355:80
    depends_on:
      - postgres
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 7354:8080
    volumes:
      - ./docs/swagger:/usr/share/nginx/html/definitions
    environment:
      API_URL: definitions/swagger.yml
    depends_on: 
      - php
networks:
  default:
